'use client'

import { useState } from 'react'

export default function VerifyPage(){
  const [code,setCode]=useState('')
  const [verified,setVerified]=useState(false)
  return <main className="verify-page"><div className="card"><div className="brand">STANDSIDE</div><p className="eyebrow">AUTHENTICITY CHECK</p><h1>VERIFY PRODUCT</h1><p>Masukkan kode unik yang terdapat pada label produk STANDSIDE.</p><div className="form"><input value={code} onChange={e=>{setCode(e.target.value);setVerified(false)}} placeholder="SS-TS-000001"/><button onClick={()=>setVerified(Boolean(code.trim()))}>VERIFY</button></div>{verified&&<div className="result"><div className="check">✓</div><div><strong>STANDSIDE ORIGINAL PRODUCT</strong><span>Kode Produk : {code.toUpperCase()}</span><span>Status : <b>ORIGINAL</b></span></div></div>}<a href="/">← Kembali</a></div><style>{`.verify-page{min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 50% 30%,#242727,#080909 60%);padding:20px}.card{width:min(700px,100%);background:#101111;border:1px solid #333;padding:45px}.brand{text-align:center;font-size:24px;font-weight:900;font-style:italic;margin-bottom:35px}.card h1{font-family:'Barlow Condensed';font-size:52px;font-style:italic;margin:8px 0}.card p:not(.eyebrow){color:#999;line-height:1.6}.form{display:flex;margin-top:25px}.form input{flex:1;background:#080909;color:#fff;border:1px solid #444;padding:15px}.form button{background:#fff;color:#000;border:0;padding:0 25px;font-weight:900}.result{display:flex;gap:20px;align-items:center;border:1px solid #3d3d3d;padding:22px;margin-top:22px}.check{width:50px;height:50px;border-radius:50%;background:#36c96b;color:#fff;display:grid;place-items:center;font-size:27px}.result div:last-child{display:flex;flex-direction:column;gap:7px;font-size:11px}.result span{color:#aaa}.result b{color:#3ddc84}.card>a{display:block;margin-top:25px;color:#888;font-size:10px}@media(max-width:600px){.card{padding:28px}.form{flex-direction:column;gap:8px}.form button{padding:14px}.card h1{font-size:44px}}`}</style></main>
}
